apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-dbs
  labels:
    {{ $.Chart.Name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "busybox"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "echo Start; sleep 10; echo End"]
