apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-dbs-{{ $.Chart.Version }}
  labels:
    chart: {{ $.Chart.Name }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-dbs
          image: "busybox"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "echo Start; sleep 10; echo End"]
